name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'src/**'
      - 'package**.json'
      - 'VERSION'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    
    - name: Build and upload
      run: |
        make upload
